spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qqq1201
    url: jdbc:mysql://localhost:3306/meeting?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    #    正向工程
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
show_error: true

mybatis:
  mapper-locations: classpath:mapper/*.xml