spring:
  http:
    max-file-size: -1
    max-request-size: -1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qqq1201
    url: jdbc:mysql://localhost:3306/meeting?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowMultiQueries=true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: 120.77.200.249
    port: 6379
    password:

show_error: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lsu.chicken.room.domain

entity_path: cn.lsu.chicken.room.domain

server:
  port: 8080


appId: EzU1ASsWJZVnAtwVGENdUfhgozqm32is8AtaW6rUoPyH
sdkKey: Ehg4vSRg2cmohEEN4sPCZjCHGZdxhHBVSCfS3E86jKmd

threshold: 0.7